image: python:3.11

services:
  - name: postgres:15
    alias: postgres

variables:
  POSTGRES_DB: test_app
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_HOST_AUTH_METHOD: trust
  DATABASE_URL: postgresql://postgres:postgres@postgres:5432/test_app
  POSTGRES_HOST: postgres
  TESTING: "1"
  PYTHONPATH: "${CI_PROJECT_DIR}/backend"

stages:
  - test

before_script:
  - cd backend
  - python -m pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install pytest pytest-cov pytest-timeout pytest-xdist

test:
  stage: test
  script:
    - python -m pytest -v --cov=app --cov-report=xml --timeout=30 -n auto
  timeout: 5 minutes
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  artifacts:
    when: always
    reports:
      coverage_report:
        coverage_format: cobertura
        path: backend/coverage.xml
    paths:
      - backend/coverage.xml
      - backend/.coverage 