image: python:3.11

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.pip-cache"
  PYTHONPATH: "$CI_PROJECT_DIR/backend"

cache:
  paths:
    - .pip-cache/
    - venv/
    - frontend/node_modules/

stages:
  - test

test-backend:
  stage: test
  before_script:
    - python -V
    - python -m venv venv
    - source venv/bin/activate
    - cd backend
    - pip install -r requirements.txt
  script:
    - python -m pytest -v tests/test_health.py
  rules:
    - if: $CI_COMMIT_BRANCH
      exists:
        - backend/**/*

test-frontend:
  stage: test
  image: node:18
  cache:
    paths:
      - frontend/node_modules/
    key:
      files:
        - frontend/package-lock.json
  before_script:
    - cd frontend
    - npm ci
  script:
    - npm run test
  rules:
    - if: $CI_COMMIT_BRANCH
      exists:
        - frontend/**/* 