image: python:3.11

stages:
  - test

test-backend:
  stage: test
  script:
    - python -V
    - cd backend
    - pip install -r requirements.txt
    - python -m pytest tests/test_health.py -v
  tags: []

test-frontend:
  stage: test
  image: node:18
  script:
    - cd frontend
    - npm install
    - npm run test
  tags: [] 