image: python:3.11

services:
  - postgres:15

variables:
  POSTGRES_DB: test_app
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_HOST_AUTH_METHOD: trust
  DATABASE_URL: postgresql://postgres:postgres@postgres:5432/test_app
  TESTING: "1"

stages:
  - test

before_script:
  - cd backend
  - python -m pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install pytest pytest-cov

test:
  stage: test
  script:
    - pytest -v --cov=app
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml 