image: python:3.11

stages:
  - test
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375

services:
  - docker:dind

before_script:
  - python -V
  - python -m pip install --upgrade pip
  - pip install pytest
  - pip install -r backend/requirements.txt

test:
  stage: test
  script:
    - cd backend
    - python -m pytest -v
  only:
    - main
    - Testing

deploy:
  stage: deploy
  script:
    - apt-get update -qy
    - apt-get install -y sshpass
    - sshpass -p "$SSH_PASSWORD" scp -o StrictHostKeyChecking=no -r * root@185.139.70.62:/root/app/
    - sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no root@185.139.70.62 "bash -c 'cd /root/app && /usr/bin/docker compose down && /usr/bin/docker compose up -d'"
  only:
    - main
  environment:
    name: production 