version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    container_name: support-frontend
    volumes:
      - frontend_build:/app/dist

  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    container_name: support-backend
    environment:
      - TELEGRAM_BOT_TOKEN=7677506032:AAHEqNUr1lIUfNVbLwaWIaPeKKShsCyz3eo
      - TELEGRAM_CHAT_ID=-1002037023574
    ports:
      - "8000:8000"

  nginx:
    image: nginx:alpine
    container_name: support-nginx
    ports:
      - "80:80"
    volumes:
      - frontend_build:/usr/share/nginx/html:ro
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - frontend
      - backend

volumes:
  frontend_build:
