version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    container_name: support-frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    container_name: support-backend
    environment:
      - TELEGRAM_BOT_TOKEN=7677506032:AAHEqNUr1lIUfNVbLwaWIaPeKKShsCyz3eo
      - TELEGRAM_CHAT_ID=-1002037023574
    volumes:
      - ./backend:/app
      - sqlite_data:/app/instance
    ports:
      - "8000:8000"

volumes:
  sqlite_data:
