version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    container_name: support-frontend
    volumes:
      - frontend_build:/app/dist
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    container_name: support-backend
    environment:
      - TELEGRAM_BOT_TOKEN=7677506032:AAHEqNUr1lIUfNVbLwaWIaPeKKShsCyz3eo
      - TELEGRAM_CHAT_ID=-1002037023574
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - sqlite_data:/app/instance
    networks:
      - app-network

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: support-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - frontend_build:/usr/share/nginx/html
    networks:
      - app-network
    depends_on:
      - frontend
      - backend

networks:
  app-network:
    driver: bridge

volumes:
  sqlite_data:
  frontend_build: