version: '3.8'

services:
  backend:
    image: backend:latest
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/app
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - db
      - redis

  frontend:
    image: frontend:latest
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: