services:
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    container_name: support-frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    container_name: support-backend
    restart: unless-stopped
    environment:
      - TELEGRAM_BOT_TOKEN=7677506032:AAHEqNUr1lIUfNVbLwaWIaPeKKShsCyz3eo
      - TELEGRAM_CHAT_ID=-1002037023574
    volumes:
      - ./backend:/app
      - sqlite_data:/app/instance
    expose:
      - "8000"

  nginx:
    image: nginx:alpine
    container_name: support-nginx
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8080:80"
    depends_on:
      - frontend
      - backend

volumes:
  sqlite_data:
