version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: support-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - support-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: support-backend
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres/support_db
    depends_on:
      - postgres
    networks:
      - support-network

  postgres:
    image: postgres:15
    container_name: support-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=support_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - support-network

networks:
  support-network:
    driver: bridge

volumes:
  postgres_data: