version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend/Dockerfile
    container_name: support-frontend
    restart: unless-stopped
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: ../docker/backend/Dockerfile
    container_name: support-backend
    restart: unless-stopped
    environment:
      - TELEGRAM_BOT_TOKEN=7677506032:AAHB2QtrxKdgUXLWlE2xXaVxs9V7BPz1fhc
      - TELEGRAM_CHAT_ID=5057752127
    volumes:
      - ./backend:/app
      - sqlite_data:/app/instance

  nginx:
    image: nginx:alpine
    container_name: support-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - frontend_build:/usr/share/nginx/html
    depends_on:
      - frontend
      - backend

volumes:
  sqlite_data:
  frontend_build: