version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: support-nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - frontend_build:/usr/share/nginx/html
    depends_on:
      - frontend
      - backend

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    container_name: support-frontend
    volumes:
      - frontend_build:/app/dist

  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    container_name: support-backend
    restart: unless-stopped
    environment:
      - TELEGRAM_BOT_TOKEN=7677506032:AAHEqNUr1lIUfNVbLwaWIaPeKKShsCyz3eo
      - TELEGRAM_CHAT_ID=-1002037023574
    volumes:
      - ./backend:/app
      - sqlite_data:/app/instance
    expose:
      - "8000"

volumes:
  sqlite_data:
  frontend_build:
